=== Jossie7/UD4/Actividad1_Libreria/BibliotecaMejorada.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Biblioteca">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="prestamos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="prestamos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="lector" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="libro" />
				<xs:element ref="fecha_prestamo" />
				<xs:element ref="fecha_retorno" />
				<xs:element ref="observaciones" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lector">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombres" />
				<xs:element ref="apellidos" />
				<xs:element ref="NIE" />
				<xs:element ref="domicilio" />
				<xs:element ref="fecha_nac" />
				<xs:element ref="afiliado" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:simpleType name="id">
		<xs:restriction base="xs:string">
			<xs:length value="5"/>
			<xs:pattern value="[A-Z].*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="nombres" type="xs:string" />
	<xs:element name="apellidos" type="xs:string" />
	<xs:element name="NIE" type="xs:string" />
	<xs:element name="domicilio" type="xs:string" />
	<xs:element name="fecha_nac" type="xs:date" />
	<xs:element name="afiliado" type="xs:boolean" />
    <xs:simpleType name="NIE">
		<xs:restriction base="xs:string">
			<xs:length value="9"/>
			<xs:pattern value="[A-Z].*"/>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="afiliado">
		<xs:restriction base="xs:boolean">
			<xs:pattern value="sÃ­"/>
			<xs:pattern value="no"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="libro">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="editorial" />
				<xs:element ref="nombre" />
				<xs:element ref="genero" />
				<xs:element ref="autor" />
				<xs:element ref="nEjemplares" />
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:simpleType name="codigo">
		<xs:restriction base="xs:string">
			<xs:length value="5"/>
			<xs:pattern value="cod\d{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="editorial" type="xs:string" />
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="genero" type="xs:string" />
	<xs:element name="autor">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="nacionalidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="nEjemplares" type="xs:integer" />
	<xs:element name="fecha_prestamo" type="xs:dateTime" />
	<xs:element name="fecha_retorno" type="xs:dateTime" />
	<xs:element name="observaciones" type="xs:string" />
</xs:schema>

=== Jossie7/UD4/Actividad1_Libreria/ValBibliotecaMejorada.xml
<?xml version="1.0" encoding="UTF-8"?>
<Biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="BibliotecaMejorada.xsd">
    <prestamos>
        <lector id="A7425"> 
            <nombres> Bryan  </nombres>
            <apellidos> Rojas </apellidos>
            <NIE> L18245224 </NIE>
            <domicilio> El Prado N° 39 </domicilio>
            <fecha_nac>2003-07-04 </fecha_nac>
            <afiliado>false</afiliado>
        </lector>
        <libro codigo = "cod89">
            <editorial>Alfaguara</editorial>
            <nombre> Conversación en la Catedral </nombre>
            <genero> Drama </genero>
            <autor nacionalidad = "peruana"> Mario Vargas Llosa </autor>
            <nEjemplares> 4 </nEjemplares>
        </libro>
        <fecha_prestamo> 2022-04-02T16:45:52 </fecha_prestamo>
        <fecha_retorno> 2022-05-01T18:00:00 </fecha_retorno>
        <observaciones> Hojas rotas y amarillentas</observaciones>
    </prestamos>
    <prestamos>
        <lector id="Z1859"> 
            <nombres> Fabian </nombres>
            <apellidos> Díaz </apellidos>
            <NIE> C74925973 </NIE>
            <domicilio> Los Callejones 25 </domicilio>
            <fecha_nac>2002-02-28</fecha_nac>
            <afiliado>true</afiliado>
        </lector>
        <libro codigo = "cod26">
            <editorial>Limonera</editorial>
            <nombre> Divina Comedia </nombre>
            <genero> Tragedia </genero>
            <autor nacionalidad = "peruana"> César Vallejo </autor>
            <nEjemplares> 2 </nEjemplares>
        </libro>
        <fecha_prestamo> 2021-02-06T11:23:11 </fecha_prestamo>
        <fecha_retorno> 2020-03-01T21:15:00 </fecha_retorno>
        <observaciones> Libro en buenas condiciones</observaciones>
    </prestamos>
    <prestamos>
        <lector id="F2598"> 
            <nombres> Joselin </nombres>
            <apellidos> Consuelo </apellidos>
            <NIE> G41209390 </NIE>
            <domicilio> Pueblo Blancos 45 </domicilio>
            <fecha_nac>1987-04-01 </fecha_nac>
            <afiliado>true</afiliado>
        </lector>
        <libro codigo = "cod78">
            <editorial>Rio</editorial>
            <nombre> Platero y yo </nombre>
            <genero> lírico </genero>
            <autor nacionalidad = "puertorriqueño"> Juan Ramón Jiménez </autor>
            <nEjemplares> 16 </nEjemplares>
        </libro>
        <fecha_prestamo> 2023-01-03T12:59:10 </fecha_prestamo>
        <fecha_retorno> 2023-01-09T23:59:59 </fecha_retorno>
        <observaciones> Portada rayada con bolígrafo </observaciones>
    </prestamos>
</Biblioteca>
