=== Jossie7/UD4/Actividad2_Concesionario/ConcesionarioMejorado.dtd
<!ELEMENT concesionario (Nombre, ciudad, informe_ventas*)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT informe_ventas (venta*)>
<!ELEMENT venta (empleado*,cliente*,coche*,formaPago,observaciones,opcionGarantia)>
<!ELEMENT empleado (nombre, apellido, edad, DNI, teléfono,fecha_incorporacion )>
<!ATTLIST empleado id CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT DNI (#PCDATA)>
    <!ELEMENT teléfono (#PCDATA)>
    <!ELEMENT fecha_incorporacion (#PCDATA)>
<!ELEMENT cliente (nombres,apellidos,NIE,telef,NSS?, direccion, poblacion, codigoPostal, fecha_nacimiento)>
<!ATTLIST cliente codigo CDATA #REQUIRED>
    <!ELEMENT nombres (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT NIE (#PCDATA)>
    <!ELEMENT telef (#PCDATA)>
    <!ELEMENT NSS (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>
    <!ELEMENT codigoPostal (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT coche (matricula,marca,modelo,cilindrada,potencia, color, motor, fechaFabricacion, precio)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT cilindrada (#PCDATA)>
    <!ELEMENT potencia (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT motor (#PCDATA)>
    <!ELEMENT fechaFabricacion (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
<!ELEMENT formaPago (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT opcionGarantia (#PCDATA)>

=== Jossie7/UD4/Actividad2_Concesionario/ConcesionarioMejorado.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "ConcesionarioMejorado.dtd">
<concesionario>
    <Nombre> </Nombre>
    <ciudad> </ciudad>
    <informe_ventas>
        <venta>
            <empleado id= "45"> 
                <nombre> Pepito  </nombre>
                <apellido> Juarez </apellido>
                <edad> 32 </edad>
                <DNI> 41813658D </DNI>
                <teléfono> 6485639 </teléfono>
                <fecha_incorporacion>02-05-2021</fecha_incorporacion>
            </empleado>
            <cliente codigo="JZ143">
                <nombres> Moises Jesus</nombres>
                <apellidos> Morales Duarez </apellidos>
                <NIE> 85478963C</NIE>
                <telef> 6541258</telef>
                <NSS> "" </NSS>
                <direccion> Prado 39 </direccion>
                <poblacion> Ubrique </poblacion>
                <codigoPostal> 11600 </codigoPostal>
                <fecha_nacimiento> 07-04-1983 </fecha_nacimiento>
            </cliente>
            <coche>
                <matricula> 1111-BAB </matricula>
                <marca> Renault </marca>
                <modelo> Passat </modelo>
                <cilindrada> 1,4 </cilindrada>
                <potencia> 82</potencia>
                <color> grismar10 </color>
                <motor> diesel </motor>
                <fechaFabricacion> 12-12-1990 </fechaFabricacion>
                <precio> 7500,10</precio>
            </coche>
            <formaPago> efectivo/banco/internet</formaPago>
            <observaciones> El coche tiene algunos defectos </observaciones>
            <opcionGarantia> sí </opcionGarantia>
        </venta>
    </informe_ventas>
</concesionario>
