=== Jossie7/UD4/Actividad6_Modulos/Modulos.dtd
<!ELEMENT Modulos (modulo*)>
<!ELEMENT modulo (nombre, contenidos*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT contenidos (UD*)>
<!ATTLIST UD id CDATA #REQUIRED>
<!ELEMENT UD (tipo, descripcion)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== Jossie7/UD4/Actividad6_Modulos/Modulos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Modulos SYSTEM "Modulos.dtd">
<Modulos>
<modulo>
    <nombre> FOL </nombre> 
    <contenidos>
        <UD id="1"> 
            <tipo>Derecho</tipo>
            <descripcion> Informar acerca de derechos laborales </descripcion>
        </UD>
        <UD id="2">
            <tipo> Programaci√≥n </tipo>
            <descripcion> Aprender JAVA </descripcion>
        </UD>
    </contenidos>  
</modulo>
</Modulos>
