=== Jossie7/UD4/Actividad6_Modulos/ModulosAvanzado.dtd
<!ELEMENT Modulos (modulo*)>
<!ELEMENT modulo (nombre, tutor, aula, cursos*,posibilidadBeca)>
<!ATTLIST modulo cod CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tutor (#PCDATA)>
<!ELEMENT aula (#PCDATA)>
<!ELEMENT posibilidadBeca (#PCDATA)>
<!ELEMENT cursos (curso*)>
<!ELEMENT curso (name, profesor,horas_semanales, UDS*,alumnosInscritos,promedioGeneral)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT horas_semanales (#PCDATA)>
<!ELEMENT alumnosInscritos (#PCDATA)>
<!ELEMENT promedioGeneral (#PCDATA)>
<!ATTLIST name nSerie CDATA #REQUIRED>
<!ELEMENT UDS (Ud*)>
<!ELEMENT Ud (numero, tema,actividades, fechaExamen)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT actividades (#PCDATA)>
<!ELEMENT fechaExamen (#PCDATA)>

=== Jossie7/UD4/Actividad6_Modulos/ModulosAvanzados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Modulos SYSTEM "ModulosAvanzado.dtd">
<Modulos>
    <modulo cod="">
        <nombre> Desarrollo de aplicaciones web </nombre>
        <tutor> Ana </tutor>
        <aula> DAW1 </aula>
        <cursos>
            <curso>
                <name nSerie=""> Lenguaje de Marcas </name>
                <profesor> Ana Gonzales </profesor>
                <horas_semanales> 4 </horas_semanales>
                <UDS>
                    <Ud> 
                        <numero> 1 </numero>
                        <tema> HTML </tema>
                        <actividades> Crear el html de un cuerpo</actividades>
                        <fechaExamen> 2023-02-02 </fechaExamen>
                    </Ud>
                    <Ud> 
                        <numero> 2 </numero>
                        <tema> XML </tema>
                        <actividades> Crear el xml de una biblioteca</actividades>
                        <fechaExamen> 2023-01-07 </fechaExamen>
                    </Ud>
                </UDS>
                <alumnosInscritos> 18 </alumnosInscritos>
                <promedioGeneral> 7.32 </promedioGeneral>   
            </curso>
            <curso>
                <name nSerie=""> Programacion </name>
                <profesor> Frenacisco</profesor>
                <horas_semanales> 6 </horas_semanales>
                <UDS>
                    <Ud> 
                        <numero> 1 </numero>
                        <tema> pseudocodigo </tema>
                        <actividades> Itinerancias </actividades>
                        <fechaExamen> 2023-02-16</fechaExamen>
                    </Ud>
                    <Ud> 
                        <numero> 2 </numero>
                        <tema> java </tema>
                        <actividades> Crear clases y objetos</actividades>
                        <fechaExamen> 2023-02-25 </fechaExamen>
                    </Ud>
                </UDS>
                <alumnosInscritos> 17 </alumnosInscritos>
                <promedioGeneral> 5.04 </promedioGeneral>
            </curso>
        </cursos>
        <posibilidadBeca> true </posibilidadBeca>
    </modulo>
    <modulo cod="">
        <nombre> Asistencia a la Direccion </nombre>
        <tutor> Pepita Perez </tutor>
        <aula> AD12 </aula>
        <cursos>
            <curso>
                <name nSerie=""> Derecho empresarial</name>
                <profesor> Julia Rocio </profesor>
                <horas_semanales> 6 </horas_semanales>
                <UDS>
                    <Ud> 
                        <numero> 1 </numero>
                        <tema> Drecho laboral </tema>
                        <actividades> Realizar una entrevista </actividades>
                        <fechaExamen> 2022-12-12 </fechaExamen>
                    </Ud>
                    <Ud> 
                        <numero> 2 </numero>
                        <tema> Gestoria </tema>
                        <actividades> Realizar una simliacion de un juicio </actividades>
                        <fechaExamen> 2024-08-08 </fechaExamen>
                    </Ud>
                </UDS>
                <alumnosInscritos> 14 </alumnosInscritos>
                <promedioGeneral> 7.32 </promedioGeneral>   
            </curso>
        </cursos>
        <posibilidadBeca> falso </posibilidadBeca>
    </modulo>
</Modulos>
