=== Jossie7/UD4/Actividad5_Practicas/practicas.dtd
<!ELEMENT practicas (alumno*)>
<!ELEMENT alumno (NIF,resultado,observaciones*,IP_MAC)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT observaciones (anhos,poblacion,enfermedad)>
<!ELEMENT anhos (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT enfermedad (#PCDATA)>
<!ELEMENT IP_MAC (#PCDATA)>

=== Jossie7/UD4/Actividad5_Practicas/practicas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE practicas SYSTEM "practicas.dtd">
<practicas>
	<alumno>
		<NIF>95555555K</NIF>
		<resultado>Apto</resultado>
		<observaciones>
			<anhos>20</anhos>
			<poblacion>Lugo</poblacion>
			<enfermedad>ukuk</enfermedad>
		</observaciones>
		<IP_MAC>172.168.1.1</IP_MAC> <!-- Los alumnos tienen IP o MAC pero no ambas -->
	</alumno>
</practicas>
