=== Jossie7/UD4/Actividad4_Clientes/Clientes.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/Clientes" elementFormDefault="qualified" targetNamespace="http://tempuri.org/Clientes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Clientes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="sede" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sede">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="direcciones" />
				<xs:element ref="empleado" />
				<xs:element ref="fecha_alta" />
				<xs:element ref="descripcion_cliente" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cliente" />
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="codigo">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z]([A-Za-z0-9]){7}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="direcciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="direccion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="direccion" type="xs:string" />
	<xs:element name="empleado" type="xs:string" />
	<xs:element name="fecha_alta" type="xs:string" />
	<xs:element name="descripcion_cliente" type="xs:string" />
	<xs:element name="cliente">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="numero_viv" />
				<xs:element ref="coste" />
				<xs:element ref="resumen" />
				<xs:element ref="plazo" />
			</xs:sequence>
			<xs:attribute name="codigoCliente" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="codigoCliente">
		<xs:restriction base="xs:string">
			<xs:pattern value="dfd"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="numero_viv" type="xs:string" />
	<xs:element name="coste" type="xs:string" />
	<xs:element name="resumen" type="xs:string" />
	<xs:element name="plazo" type="xs:string" />
</xs:schema>

=== Jossie7/UD4/Actividad4_Clientes/ClientesValidacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Clientes.xsd">
    <sede codigo ="A7492597">
        <direcciones>
            <direccion>El Prado NÂº39</direccion>
            <direccion> </direccion>
        </direcciones>
        <empleado id="1">
            <nombre>Pepito</nombre>
            <apellido>Perez</apellido>
        </empleado>   
        <fecha_alta>2023-04-07</fecha_alta>
        <descripcion_cliente>solvente</descripcion_cliente>
        <cliente codigoCliente="ABC-743">
            <numero_viv>2</numero_viv> 
            <coste>1000.25</coste>
            <resumen>Se encuentra en buenas condiciones</resumen>
            <plazo>30</plazo>   
        </cliente>
    </sede>
</Clientes>
