=== Jossie7/UD4/Actividad4_Clientes/Clientes_avanzado.dtd
<!ELEMENT Clientes (sede*)>
<!ELEMENT sede (direcciones*, empleado*, fecha_alta,cliente*)>
<!ATTLIST sede codigo CDATA #REQUIRED>
<!ELEMENT direcciones (direccion*)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT empleado (nombres, apellidos,puesto,poblacion,edad,fecha_nacimiento)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ATTLIST empleado id  CDATA #REQUIRED>
<!ELEMENT fecha_alta (#PCDATA)>
<!ELEMENT cliente (nombre,apellido,trabajo, historial,descripcion_cliente,numero_viv,vivienda*,seguroSocial*, aprobacion)>
<!ATTLIST cliente codigo NMTOKEN  #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT trabajo (#PCDATA)>
<!ELEMENT historial (#PCDATA)>
<!ELEMENT descripcion_cliente (#PCDATA)>
<!ELEMENT numero_viv (#PCDATA)>
<!ELEMENT aprobacion (#PCDATA)>
<!ELEMENT vivienda (antiguedad_anhos,coste,resumen,plazo)>
<!ATTLIST vivienda id  CDATA #REQUIRED>
<!ELEMENT antiguedad_anhos (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>
<!ELEMENT seguroSocial (nivel,categoria)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ATTLIST seguroSocial nss  CDATA #REQUIRED>

=== Jossie7/UD4/Actividad4_Clientes/Clientes_avanzado.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clientes SYSTEM "Clientes_avanzado.dtd">
<Clientes>
    <sede codigo ="A7492597">
        <direcciones>
            <direccion>El Prado NÂº39</direccion>
            <direccion> </direccion>
        </direcciones>
        <empleado id="1">
            <nombre>Pepito</nombre>
            <apellido>Perez</apellido>
        </empleado>   
        <fecha_alta>2023-04-07</fecha_alta>
        <cliente codigo="ABC-743">
            <descripcion_cliente>solvente</descripcion_cliente>
            <numero_viv>2</numero_viv> 
            <vivienda id="001"> 
                <coste>1000,25</coste>
                <resumen>Se encuentra en buenas condiciones</resumen>
                <plazo>30</plazo>   
            </vivienda>
        </cliente>
    </sede>
</Clientes>
