=== Jossie7/UD4/Actividad4_Clientes/Clientes_avanzado.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Clientes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="sede" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sede">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="direcciones" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="empleado" />
				<xs:element ref="fecha_alta" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cliente" />
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="direcciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="direccion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="direccion" type="xs:string" />
	<xs:element name="empleado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombres" />
				<xs:element ref="apellidos" />
				<xs:element ref="puesto" />
				<xs:element ref="poblacion" />
				<xs:element ref="edad" />
				<xs:element ref="fecha_nacimiento" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:simpleType name="puesto">
		<xs:restriction base="xs:string">
			<xs:enumeration value="secretario"/>
			<xs:enumeration value="supervisor"/>
            <xs:enumeration value="inmobiliario"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="nombres" type="xs:string" />
	<xs:element name="apellidos" type="xs:string" />
	<xs:element name="puesto" type="xs:string" />
	<xs:element name="poblacion" type="xs:string" />
	<xs:element name="edad" type="xs:integer" />
	<xs:element name="fecha_nacimiento" type="xs:date" />
	<xs:element name="fecha_alta" type="xs:date" />
	<xs:element name="cliente">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="apellido" />
				<xs:element ref="trabajo" />
				<xs:element ref="historial" />
				<xs:element ref="descripcion_cliente" />
				<xs:element ref="numero_viv" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="vivienda" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="seguroSocial" />
				<xs:element ref="aprobacion" />
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:NMTOKEN" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:simpleType name="descripcion_cliente">
		<xs:restriction base="xs:string">
			<xs:enumeration value="procedente"/>
			<xs:enumeration value="improcedente"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="apellido" type="xs:string" />
	<xs:element name="trabajo" type="xs:string" />
	<xs:element name="historial" type="xs:string" />
	<xs:element name="descripcion_cliente" type="xs:string" />
	<xs:element name="numero_viv" type="xs:integer" />
	<xs:element name="aprobacion" type="xs:boolean" />
	<xs:element name="vivienda">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="antiguedad_anhos" />
				<xs:element ref="coste" />
				<xs:element ref="resumen" />
				<xs:element ref="plazo" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="antiguedad_anhos" type="xs:integer" />
	<xs:element name="coste" type="xs:decimal" />
	<xs:element name="resumen" type="xs:string" />
	<xs:element name="plazo" type="xs:integer" />
	<xs:element name="seguroSocial">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nivel" />
				<xs:element ref="categoria" />
			</xs:sequence>
			<xs:attribute name="nss" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:simpleType name="nss">
		<xs:restriction base="xs:string">
			<xs:length value="9"/>
			<xs:pattern value="\d[A-Z]"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="nivel">
		<xs:restriction base="xs:string">
			<xs:enumeration value="alto"/>
			<xs:enumeration value="bajo"/>
            <xs:enumeration value="intermedio"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="nivel" type="xs:string" />
	<xs:element name="categoria" type="xs:string" />
</xs:schema>

=== Jossie7/UD4/Actividad4_Clientes/Clientes_avanzadoConvalidacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Clientes_avanzado.xsd">
    <sede codigo ="G89">
        <direcciones>
            <direccion>El Prado NÂº39</direccion>
            <direccion> </direccion>
        </direcciones>
        <empleado id="1">
            <nombres>Pepito</nombres>
            <apellidos>Perez</apellidos>
            <puesto> secretario </puesto>
            <poblacion> Ubrique </poblacion>
            <edad> 39 </edad>
            <fecha_nacimiento> 1989-05-05 </fecha_nacimiento>
        </empleado>   
        <fecha_alta>2023-04-07</fecha_alta>
        <cliente codigo="1236">
            <nombre> Juana </nombre>
            <apellido> Magdalena </apellido>
            <trabajo> petaquero </trabajo>
            <historial> Es nueva  cleinte con buen historial financiero </historial>
            <descripcion_cliente>procedente</descripcion_cliente>
            <numero_viv>2</numero_viv> 
            <vivienda id="001">
                <antiguedad_anhos> 3 </antiguedad_anhos>
                <coste>1000.25</coste>
                <resumen>Se encuentra en buenas condiciones</resumen>
                <plazo>30</plazo>   
            </vivienda>
            <seguroSocial nss="12589653A"> 
                <nivel> alto </nivel>
                <categoria> nivel 4 </categoria>
            </seguroSocial>
            <aprobacion> true </aprobacion>
            
        </cliente>
    </sede>
</Clientes>
